### ISSUE TITLE
Support Firecracker config via file (and not API)

### ISSUE THREAD

**Issue by richardcase** [weaveworks/flintlock#137]
**Describe the solution you'd like:**

Support configuring firecracker using a config file instead of the api. 

**Why do you want this feature:**
This will allow people to run reignite without exposing the api sock.

**Anything else you would like to add:**
This has been partially implemented via the `--disable-api` flag and [this](https://github.com/weaveworks/reignite/blob/main/infrastructure/firecracker/create.go#L51). However, it doesn't work for metadata currently as it's **blocked by**:
https://github.com/firecracker-microvm/firecracker/issues/1292

**Comment by richardcase** [comment]
This is reliant on this change to complete: https://github.com/firecracker-microvm/firecracker/pull/2758

**Comment by Callisto13** [comment]
Pr merged, we are now just blocked on getting an up-to-date fork

**Comment by richardcase** [comment]
To complete this we will need to:

* create a file containing the metadata and save it to disk along side the existing config file. See [this example](https://github.com/firecracker-microvm/firecracker/blob/main/resources/tests/metadata.json)
* use the new `--metadata` flag when starting firecracker and provide the path to the metadata file.

**Comment by richardcase** [comment]
Also, for context if the config fails then [firecracker exits](https://github.com/firecracker-microvm/firecracker/blob/3ebd8090e7e95ab769d81f0373109bd7eff89a3f/src/firecracker/src/main.rs#L514).
