### ISSUE TITLE
Use time instead of int64 for timestamps

### ISSUE THREAD

**Issue by yitsushi** [weaveworks/flintlock#149]
**Describe the solution you'd like:**
We are using timestamp as int64, but `time.Time` can be beneficial.

**Why do you want this feature:**
We can easily do time-math, like before, after, or since.

**Anything else you would like to add:**
The idea came up in this thread: https://github.com/weaveworks/reignite/pull/144#discussion_r731549085

**Comment by souleb** [comment]
I like the idea of storing a unix time on int64 and converting it to time.time when manipulation is needed. With time.time testing is difficult when it is rendered (sec, usec, leap second).

**Comment by richardcase** [comment]
Discussed going to keep int64 for our model and convert to time where needed. We will create ticket to update usage of Unix to UnixNano
