### ISSUE TITLE
Add some way for users to discover their flintlock version

### ISSUE THREAD

**Issue by Callisto13** [weaveworks/flintlock#163]
Probably can wait until we have actual releases.

**Describe the solution you'd like:**
I'd like to be able to run `flintlockd -v` or hit some endpoint on a running instance or look at some file or something to find out the version of flintlock I am using.

**Why do you want this feature:**
Our bug issue template asks people to provide their flintlock version, but there is no way for them to do this, unless they happen to remember the version they downloaded / sha they built from.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by yitsushi** [comment]
After the initial alpha release, I think this is relevant and should be done in short term.
