### ISSUE TITLE
Use forked version of firecracker

### ISSUE THREAD

**Issue by Callisto13** [weaveworks/flintlock#166]
Firecracker's [`macvtap` branch](https://github.com/firecracker-microvm/firecracker/tree/feature/macvtap) is nudging 500 commits behind `main`, and we are not sure when that feature will be merged or even what support will be available.

To avoid any nasty surprises, we are going to:

- Fork firecracker (_Richard already has a fork, so we could use that if we like_)
- Ensure that the forked `macvtap` branch is kept up with both upstream `main` and the upstream feature branch (_this can either be an automated cron job, or a manual process_)

**Comment by jmickey** [comment]
I have created ticket weaveworks/corp#2267 for this.

**Comment by richardcase** [comment]
This is still blocked on the corp ticket

**Comment by Callisto13** [comment]
I am gonna carry on with this.

- get tests running
- update docs which reference the previous branch/binary
- create action which regularly updates the fork and creates a binary
- use that binary in the nightly e2es
