### ISSUE TITLE
Enable all the disabled linters in global scope

### ISSUE THREAD

**Issue by yitsushi** [weaveworks/flintlock#168]
**Describe the solution you'd like:**
Now we have a lot of errors if we enable `wsl` for example. I put them on ignore/disabled state.

**Why do you want this feature:**
Linters are there to make the Go ecosystem more consistent.

**Anything else you would like to add:**
The list of disabled linters:

* `lll`: Reports long lines
* `gci`: Gci control golang package import order and make it always deterministic.
* `godox`: Tool for detection of FIXME, TODO and other comment keywords
* `gochecknoglobals`: check that no global variables exist
* `wsl`: Whitespace Linter - Forces you to use empty lines!

The important part is `wsl`. We should avoid globals (`gochecknoglobals`) and very long lines (`lll`). `gci` would be nice, while `godox` is questionable.

* :exclamation:  Both `wsl` and `lll` makes the code **much** easier to read. 

For `dogox`, I prefer to use issues to track Todo or Fixme items. If it's in the code it will not be fixed until someone has to touch that code block again, while without this linter it's easier to merge a pr that has a comment like
* `TODO: do we need to add validation?` add validation, file an issue, start a discussion.
* `TODO: remove this fatal`, just go and remove that Fatal. If it's not easy, file an issue.
* `TODO: validate the spec`, if it's out of the scope for the issue, but still want to capture "that's the place" than it's enough to write `Here we can validate the spec. #12345`, potentially with an already files issue id

:question:  Maybe with a "what linter settings are we using" ADR.

follow-up from: #162

**Comment by richardcase** [comment]
In the ADR make sure we say why a specific linter is disabled.
