### ISSUE TITLE
Snapshots sometimes not properly cleaned on delete

### ISSUE THREAD

**Issue by Callisto13** [weaveworks/flintlock#225]
**What happened:**
Occasionally on a delete, `containerd` fails to remove a device.

```
msg="failed to remove device" error="failed to deactivate device \"dev-thinpool-snap-2\": failed to deactivate device: device or resource busy"
```

I have seen this in CI and pretty consistently locally.

In CI ([link](https://github.com/weaveworks/flintlock/runs/4123046102?check_suite_focus=true)) the tests eventually failed while checking that the PID was no longer running after delete. (Another instance of that happening [here](https://github.com/weaveworks/flintlock/runs/4184458494?check_suite_focus=true))

Locally the test does not fail sometimes (it does fail more often than not), but the device still remains.

The reconciliation does make some attempt to clean up, but in the case of the local "leak", even though the mVM eventually died, the device stayed.

**What did you expect to happen:**

On a delete we should ensure that everything is gone.

**How to reproduce it:**

- Start containerd
- Start flintlock
- Create mvm: `./hack/scripts/send.sh -m CreateMicroVM`
- Get it `./hack/scripts/send.sh -m GetMicroVM`
- Delete it : `./hack/scripts/send.sh -m DeleteMicroVM`
- Observe the logs from containerd:
   ```
   WARN[2021-11-26T12:23:06.066934932Z] failed to deactivate device, retrying... (10 of 100)  error="device or resource busy"
   WARN[2021-11-26T12:23:55.593179253Z] failed to deactivate device, retrying... (20 of 100)  error="device or resource busy"
   etc ...
   ```
- Get the mvm again: `./hack/scripts/send.sh -m GetMicroVM`
- See that it fails, because according to flintlock the mvm is gone
- Look for the firecracker process: `ps aux | grep fire`
- See that it is not, in fact, gone
- Kill the pid: `sudo kill -9 <pid>`
- See that now the logs continue and containerd is fine, the mvm is actually deleted

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- flintlock version:
- OS (e.g. from `/etc/os-release`):

**Comment by richardcase** [comment]
Q: maybe an option to add to cleanup command

**Comment by souleb** [comment]
I can work on this ☝️

**Comment by Callisto13** [comment]
All yours 👍 . We have shiny new [contrib](https://github.com/weaveworks/flintlock/blob/main/CONTRIBUTING.md) docs too ✨

**Comment by Callisto13** [comment]
@souleb how are doing with this? We have bumped up the priority and added to the "Demo ready" Epic as it is happening consistently. LMK if you don't think you will have time for it in the next week.

**Comment by souleb** [comment]
I will be working on it this week.

**Comment by Callisto13** [comment]
Just added some more repro details. I think we have 2 problems here:
1. We remove the mvm state file _way_ to early: Flintlock has no idea that the firecracker pid is still running, but according to the API the mvm does not exist anymore, so the end use cannot know unless they are staring at the logs
2. We need to ensure the mvm process actually dies when we tell it to, before we go on doing anything else

**Comment by souleb** [comment]
I saw that the `SendCtrlAltDel` + `os.Interrupt` has been replaced by a `SIGHUP`, do you know why? I have added a way to wait for the `mvm` process to exit, so we make sure we delete the snapshot only on clean exit

**Comment by Callisto13** [comment]
That change came as part of [this work](https://github.com/weaveworks/flintlock/pull/288) to start firecracker mvms via a config file rather than an API socket. The context for SIGHUP is here https://weaveworks.slack.com/archives/C01SYJ779SR/p1637768490269900

**Comment by souleb** [comment]
Thanks. Now do we want only the graceful shutdown, and hang on `wait` until the `mvm` process exit(with timeout)? Or do we want to kill when `SIGHUP` does not work(ignored, hanging; etc...)?

**Comment by richardcase** [comment]
I think if the process doesn't stop after a `SIGHUP`  then we should forcibly kill the process. Perhaps making the time to wait configurable when starting flintlock.

**Comment by souleb** [comment]
> I think if the process doesn't stop after a `SIGHUP` then we should forcibly kill the process. Perhaps making the time to wait configurable when starting flintlock.

That sounds good to me. I'll add that to the PR.
