### ISSUE TITLE
Create network interfaces in namespace

### ISSUE THREAD

**Issue by yitsushi** [weaveworks/flintlock#237]
**Describe the solution you'd like:**
Both Tap and Macvtap interfaces can be created in a specific namespace, they can live under a namespace related to the namespace of the VM.

**Why do you want this feature:**
Mostly: No `TODO` comments should live in the code without filed issues to track them.

**Anything else you would like to add:**
* https://github.com/weaveworks/flintlock/blob/main/infrastructure/network/network_service.go#L58
* https://github.com/weaveworks/flintlock/blob/main/infrastructure/network/network_service.go#L69

**Comment by richardcase** [comment]
This is a duplicate of #206
