### ISSUE TITLE
Mvm status should reflect usability of mvm

### ISSUE THREAD

**Issue by Callisto13** [weaveworks/flintlock#286]
**What happened:**
A recent issue highlighted the fact that while we report that a Mvm is "Created" it is not actually useable (in this case it had not started.

**What did you expect to happen:**
We should reflect to the user that the mvm is totally 100% ready and usable.

**How to reproduce it:**
check out to https://github.com/weaveworks/flintlock/commit/126e514ec9f856051505cf9807c853fecced1f5d and create a microvm using `./hack/scripts/send.sh -m CreateMicroVM`.

When you get the mvm (`./hack/scripts/send.sh -m GetMicroVM`), it will say created, but when looking at the flintlock logs and the logs at `/var/lib/flintlock/vm/ns1/mvm1/firecracker.stderr` you will see that the mvm never started, so it is useless to a user.

**Anything else you would like to add:**
 A user should be able to get an accurate status of the mvm without trawling through logs

**Environment:**

- flintlock version:
- containerd version:
- OS (e.g. from `/etc/os-release`):

**Comment by Callisto13** [comment]
@yitsushi believe this problem is solved by the config file correct?

**Comment by yitsushi** [comment]
Partially, but I think the #198 is required to fully cover this issue. Or was it more about the initial start and not if it dies later, but resync did not happen yet?

**Comment by Callisto13** [comment]
Ah yeh I forgot about the supervisor plan. I wrote this when I was having trouble with vms being marked Created too fast, but yes I suppose it does relate to having an accurate view of all lifecycle events and current conditions. I think let's close this in favour of the Supervisor one
