### ISSUE TITLE
GetAllMicroVMs does not filter for namespace

### ISSUE THREAD

**Issue by Callisto13** [weaveworks/flintlock#311]
**What happened:**
I created a mvm in namespace `foo`.
I ran ListMicroVMs pointing to namespace `bar`.

All mvms were returned (ie those in `foo`)

**What did you expect to happen:**
In this example, nothing should have been returned on the list call as I did not create anything in the `bar` namespace.

**How to reproduce it:**
Follow steps above.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- flintlock version: compiled off main at `819bbaf`
- containerd version:
- OS (e.g. from `/etc/os-release`):

**Comment by yitsushi** [comment]
Fixed by #369
