### ISSUE TITLE
Set ordered names for guest devices

### ISSUE THREAD

**Issue by Callisto13** [weaveworks/flintlock#340]
~We default the metadata device to `mds0`, yet firecracker seems to do what it wants and always creates it as `eth0`. Rude.~

~So we should either:~
- ~Find out why/where we are being ignored and stop it, or~
- ~Just give in and use set `eth0` (we would then have to ensure that none of the other network interfaces use `eth0`)~

~This is not causing a problem that we can see just yet, but it may in the future and it is confusing to debug.~

Update: this is by design https://weaveworks.slack.com/archives/C01SYJ779SR/p1641379724304500

**Comment by yitsushi** [comment]
* We will rely on the order specified in the incoming grpc request and the fact that serialization in go shouldn't change the order
* We will update flintlock docs to say that if you care about the order of your network interfaces then you must specify them in the order from eth1,eth2,ethX
* mmds device is the first (eth0)


> There is no relation between the numbering of the /network-interface API calls and the number of the network interface in the guest. Rather, it is usually the order of network interface creation that determines the number in the guest (but this depends on the distribution).
> 
> For example, when you create two network interfaces by calling /network-interfaces/1 and then /network-interfaces/0, it may result in this mapping:
>
> /network-interfaces/1 -> eth0
> /network-interfaces/0 -> eth1
>
> Source: https://github.com/firecracker-microvm/firecracker/blob/83ec483d4254936e1e2fd4adfe94761611a74a93/FAQ.md#how-does-network-interface-numbering-work
