### ISSUE TITLE
Match Firecracker API with the 1.0.0 release

### ISSUE THREAD

**Issue by yitsushi** [weaveworks/flintlock#384]
**What happened:**

Firecracker v1.0.0 changed some fields we are using.

**What did you expect to happen:**
Unable to start MicroVM

**How to reproduce it:**
Use Firecracker 1.0.0

**Anything else you would like to add:**
Relevant changelog entries on Firecracker:

> * Remove allow_mmds_requests field from the request body that attaches network interfaces. Specifying interfaces that allow forwarding requests to MMDS is done by adding the network interface's ID to the network_interfaces field of PUT /mmds/config request's body.
> * Renamed /machine-config ht_enabled to smt.
> * smt field is now optional on PUT /machine-config, defaulting to false.

Source: https://github.com/firecracker-microvm/firecracker/blob/d3e98b9a4ae024de63f072c57015d8b7b0c1b061/CHANGELOG.md#100

**Environment:**

- flintlock version:
- containerd version:
- OS (e.g. from `/etc/os-release`):

**Comment by richardcase** [comment]
For the mmds change we need to:

- Ensure we generate a `mmds-config` section in the config file we generate. See [this](https://github.com/firecracker-microvm/firecracker/blob/3e217c19abaea275138ac13a4be0f85b834ec246/src/vmm/src/resources.rs#L83)
- Fill in the mmdconfig fields (i.e. version, network_interfaces, ipv4_address) when we generate the config file. See [this](https://github.com/firecracker-microvm/firecracker/blob/f35f324b84ce5c78dcf706cd97117bca41485b34/src/vmm/src/vmm_config/mmds.rs#L13)
