### ISSUE TITLE
Add code scanning with CodeQL

### ISSUE THREAD

**Issue by richardcase** [weaveworks/flintlock#84]
**Describe the solution you'd like:**
We need to add code scanning using CodeQL

**Why do you want this feature:**

**Anything else you would like to add:**
https://docs.github.com/en/code-security/code-scanning/using-codeql-code-scanning-with-your-existing-ci-system/about-codeql-code-scanning-in-your-ci-system

**Comment by yitsushi** [comment]
Is this more than enabling codeql from github settings?

**Comment by richardcase** [comment]
Its mainly creatind a new GHA workflow to do CodeQL analysis on a schedule
