### ISSUE TITLE
Initial creation of documentation site

### ISSUE THREAD

**Issue by richardcase** [weaveworks/flintlock#85]
**Describe the solution you'd like:**
Create the infrastructure and base documentation site. The docs should have their source in the main and publish to netflify or GitHub pages

**Why do you want this feature:**

**Anything else you would like to add:**

We could follow the approach used by CAPI/CAPA

**Comment by yitsushi** [comment]
Created a PR to enable github pages on the repo: https://github.com/weaveworks/corp/pull/2247

**Comment by yitsushi** [comment]
Follow-up: #194
